// AUTO-GENERATED by sqlx-js. Do not edit.
// Run `sqlx-js prepare` to regenerate.

export const UserRole = {
  ["admin"]: "admin",
  ["editor"]: "editor",
  ["viewer"]: "viewer",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const DbEnums = {
  ["public.user_role"]: UserRole,
} as const;

export type DbEnumName = keyof typeof DbEnums;

export type DbEnumValue<Name extends DbEnumName> =
  Name extends DbEnumName
    ? (typeof DbEnums)[Name][keyof (typeof DbEnums)[Name]]
    : never;
