// AUTO-GENERATED by sqlx-js. Do not edit.
// Run `sqlx-js prepare` to regenerate.

export interface SqlxJsGeneratedQueries {
  "DELETE FROM posts\n     WHERE user_id = $1 AND status = 'archived'\n     RETURNING id AS post_id, user_id, status": { params: [bigint]; row: { "post_id": bigint; "user_id": bigint; "status": "draft" | "published" | "archived" } };
  "INSERT INTO posts (user_id, title) VALUES ($1, $2) RETURNING id AS \"id!\"": { params: [bigint, string]; row: { "id": bigint } };
  "INSERT INTO users (name, email, age) VALUES ($1, $2, $3) RETURNING id AS \"id!\", created_at AS \"created_at!\"": { params: [string, string, number | null]; row: { "id": bigint; "created_at": import("@onreza/sqlx-js").PgTemporal } };
  "INSERT INTO users (name, email, role) VALUES ($1, $2, $3) RETURNING id AS \"id!\"": { params: [string, string, "admin" | "editor" | "viewer"]; row: { "id": bigint } };
  "INSERT INTO users (name, email, role) VALUES ($1, $2, $3) RETURNING id AS \"id!\", role AS \"role!\"": { params: [string, string, "admin" | "editor" | "viewer"]; row: { "id": bigint; "role": "admin" | "editor" | "viewer" } };
  "INSERT INTO users (name, email, settings) VALUES ($1, $2, $3) RETURNING id AS \"id!\"": { params: [string, string, import("@onreza/sqlx-js").JsonParameter<SqlxJsJson.UserSettings>]; row: { "id": bigint } };
  "INSERT INTO users (name, email)\n     VALUES ($1, $2)\n     ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name\n     RETURNING id AS user_id, name AS user_name, email AS user_email, role AS user_role": { params: [string, string]; row: { "user_id": bigint; "user_name": string; "user_email": string; "user_role": "admin" | "editor" | "viewer" } };
  "INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id AS \"id!\"": { params: [string, string]; row: { "id": bigint } };
  "SELECT\n       u.id AS user_id,\n       u.email AS user_email,\n       u.role AS user_role,\n       COUNT(p.id) AS post_count,\n       MAX(p.id) AS latest_post_id\n     FROM users u\n     LEFT JOIN posts p ON p.user_id = u.id\n     GROUP BY u.id, u.email, u.role\n     ORDER BY u.id DESC\n     LIMIT $1::int OFFSET $2::int": { params: [number, number]; row: { "user_id": bigint; "user_email": string; "user_role": "admin" | "editor" | "viewer"; "post_count": bigint; "latest_post_id": bigint | null } };
  "SELECT\n     id AS \"id!\",\n     name AS \"name!\",\n     email AS \"email!\",\n     role AS \"role!\",\n     created_at AS \"createdAt!\"\n   FROM public.list_users(\n     COALESCE($role, NULL::public.user_role),\n     COALESCE($search, NULL::text),\n     COALESCE($afterId, NULL::bigint),\n     $limit\n   )": { params: { "role": "admin" | "editor" | "viewer" | null; "search": string | null; "afterId": bigint | null; "limit": number }; row: { "id": bigint; "name": string; "email": string; "role": "admin" | "editor" | "viewer"; "createdAt": import("@onreza/sqlx-js").PgTemporal } };
  "SELECT 1 AS one, 'literal'::text AS msg, now() AS ts FROM users LIMIT 1": { params: []; row: { "one": number; "msg": string; "ts": import("@onreza/sqlx-js").PgTemporal } };
  "SELECT COUNT(*) AS \"n!\" FROM users": { params: []; row: { "n": bigint } };
  "SELECT COUNT(*) AS \"n!\" FROM users WHERE age >= $1": { params: [number]; row: { "n": bigint } };
  "SELECT COUNT(*) AS n FROM users": { params: []; row: { "n": bigint } };
  "SELECT id AS \"id!\", name AS \"name!\" FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string } };
  "SELECT id AS \"id!\", name AS \"name!\", email AS \"email!\", age, bio FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string; "email": string; "age": number | null; "bio": string | null } };
  "SELECT id AS user_id, name AS user_name, email AS user_email\n     FROM users\n     WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')\n     ORDER BY id\n     LIMIT $2::int": { params: [string | null, number]; row: { "user_id": bigint; "user_name": string; "user_email": string } };
  "SELECT id FROM users WHERE role = $1": { params: ["admin" | "editor" | "viewer"]; row: { "id": bigint } };
  "SELECT id, age FROM users WHERE age = $1": { params: [number]; row: { "id": bigint; "age": number } };
  "SELECT id, age FROM users WHERE age IN (18, 21, 25)": { params: []; row: { "id": bigint; "age": number } };
  "SELECT id, bio FROM users WHERE bio IS NOT NULL AND id = $1": { params: [bigint]; row: { "id": bigint; "bio": string } };
  "SELECT id, bio FROM users WHERE bio IS NOT NULL OR id = $1": { params: [bigint]; row: { "id": bigint; "bio": string | null } };
  "SELECT id, bio, age FROM users WHERE bio IS NOT NULL AND age > $1": { params: [number]; row: { "id": bigint; "bio": string; "age": number } };
  "SELECT id, CASE WHEN age >= 18 THEN 'adult' ELSE 'minor' END AS bucket FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "bucket": string } };
  "SELECT id, COALESCE(bio, 'no bio') AS bio_or_default, COALESCE(age, 0) AS age_or_zero FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "bio_or_default": string; "age_or_zero": number } };
  "SELECT id, COALESCE(bio, 'none') AS bio_or_default, length(bio) AS bio_len FROM users WHERE bio IS NOT NULL AND id = $1": { params: [bigint]; row: { "id": bigint; "bio_or_default": string; "bio_len": number } };
  "SELECT id, name, email, age, bio FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string; "email": string; "age": number | null; "bio": string | null } };
  "SELECT id, name, email, role\n   FROM users\n   WHERE email = $email": { params: { "email": string }; row: { "id": bigint; "name": string; "email": string; "role": "admin" | "editor" | "viewer" } };
  "SELECT id, name, role FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string; "role": "admin" | "editor" | "viewer" } };
  "SELECT id, name, settings FROM users WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string; "settings": SqlxJsJson.UserSettings } };
  "SELECT id, settings FROM users WHERE settings = $1 LIMIT 1": { params: [import("@onreza/sqlx-js").JsonParameter<SqlxJsJson.UserSettings>]; row: { "id": bigint; "settings": SqlxJsJson.UserSettings } };
  "SELECT id, title, meta, attachments FROM posts WHERE id = $1": { params: [bigint]; row: { "id": bigint; "title": string; "meta": SqlxJsJson.PostMeta | null; "attachments": (SqlxJsJson.Attachment | null)[] } };
  "SELECT p.id, p.title, p.status, p.tags, p.history, u.role AS author_role FROM posts p JOIN users u ON u.id = p.user_id WHERE p.id = $1": { params: [bigint]; row: { "id": bigint; "title": string; "status": "draft" | "published" | "archived"; "tags": (string | null)[]; "history": ("admin" | "editor" | "viewer" | null)[]; "author_role": "admin" | "editor" | "viewer" } };
  "SELECT u.id AS uid, p.id AS pid FROM users u FULL OUTER JOIN posts p ON p.user_id = u.id WHERE u.id = $1 OR p.id = $1": { params: [bigint]; row: { "uid": bigint | null; "pid": bigint | null } };
  "SELECT u.id AS user_id, u.name, p.title, p.published FROM users u LEFT JOIN posts p ON p.user_id = u.id WHERE u.id = $1": { params: [bigint]; row: { "user_id": bigint; "name": string; "title": string | null; "published": boolean | null } };
  "SELECT u.id, p.title, p.body FROM users u LEFT JOIN posts p ON p.user_id = u.id WHERE p.body IS NOT NULL AND u.id = $1": { params: [bigint]; row: { "id": bigint; "title": string | null; "body": string } };
  "UPDATE posts\n     SET status = 'published', published = true\n     WHERE id = (\n       SELECT id\n       FROM posts\n       WHERE status = 'draft'\n       ORDER BY id\n       FOR UPDATE SKIP LOCKED\n       LIMIT 1\n     )\n     RETURNING id AS post_id, user_id, status, published": { params: []; row: { "post_id": bigint; "user_id": bigint; "status": "draft" | "published" | "archived"; "published": boolean } };
  "UPDATE users SET name = $1 WHERE id = $2": { params: [string, bigint]; row: never };
  "UPDATE users SET settings = $1 WHERE id = $2 RETURNING id AS \"id!\", settings": { params: [import("@onreza/sqlx-js").JsonParameter<SqlxJsJson.UserSettings>, bigint]; row: { "id": bigint; "settings": SqlxJsJson.UserSettings } };
}

export interface SqlxJsGeneratedFileQueries {
  "queries/count_posts.sql": { params: [bigint]; row: { "n": bigint } };
  "queries/get_users_by_role.sql": { params: ["admin" | "editor" | "viewer", number]; row: { "id": bigint; "name": string; "email": string } };
}

export interface SqlxJsGeneratedFunctions {
  "public.list_users(filter_role user_role, search_text text, after_id bigint, result_limit integer)": { kind: "function"; params: ["admin" | "editor" | "viewer", string, bigint, number]; returns: { id: bigint | null; name: string | null; email: string | null; role: "admin" | "editor" | "viewer" | null; created_at: import("@onreza/sqlx-js").PgTemporal | null }; returnsSet: true; volatility: "stable"; securityDefiner: false; leakproof: false; parallelSafety: "unsafe"; owner: "postgres"; ownerSuperuser: true; publicExecute: true; searchPath: null; extensionOwned: false };
}

export interface SqlxJsGeneratedRuntimeTypes {
}

export interface SqlxJsGeneratedProfileQueries {
}

export interface SqlxJsGeneratedProfileFileQueries {
}

export interface SqlxJsGeneratedProfiles {
}

export interface SqlxJsGeneratedRegistry {
  queries: SqlxJsGeneratedQueries;
  fileQueries: SqlxJsGeneratedFileQueries;
  functions: SqlxJsGeneratedFunctions;
  runtimeTypes: SqlxJsGeneratedRuntimeTypes;
}

declare module "@onreza/sqlx-js" {
  interface KnownQueries extends SqlxJsGeneratedQueries {}
  interface KnownFileQueries extends SqlxJsGeneratedFileQueries {}
  interface KnownFunctions extends SqlxJsGeneratedFunctions {}
  interface KnownProfiles extends SqlxJsGeneratedProfiles {}
}

export {};
