import { expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  functionCatalogOutputPath,
  renderFunctionCatalog,
  writeFunctionCatalogModule,
} from "../src/function-catalog";
import type { FunctionEntry } from "../src/function-cache";
import { assertDistinctPrepareGeneratedOutputs } from "../src/prepare-artifacts";

function entry(identity: string): FunctionEntry {
  return {
    schema: "public",
    name: "example",
    signature: "public.example(value text)",
    identity,
    kind: "function",
    language: "sql",
    params: [{ mode: "in", name: "value", tsType: "string | null" }],
    returns: "boolean | null",
    returnsSet: false,
    volatility: "stable",
    strict: false,
    securityDefiner: false,
    leakproof: false,
    parallelSafety: "unsafe",
    owner: "app_owner",
    ownerSuperuser: false,
    publicExecute: false,
    settings: [],
    searchPath: null,
    extensionOwned: false,
  };
}

test("renders stable overload-safe function identities", () => {
  expect(renderFunctionCatalog([
    entry("billing.charge(pg_catalog.uuid,pg_catalog.text[])"),
    entry("billing.charge(pg_catalog.uuid)"),
  ])).toBe(`// AUTO-GENERATED by sqlx-js. Do not edit.
// Run \`sqlx-js prepare\` to regenerate.

export const DbFunctions = {
  "billing.charge(pg_catalog.uuid)": "billing.charge(pg_catalog.uuid)",
  "billing.charge(pg_catalog.uuid,pg_catalog.text[])": "billing.charge(pg_catalog.uuid,pg_catalog.text[])",
} as const;

export type DbFunctionIdentity = keyof typeof DbFunctions;
`);
});

test("rejects duplicate function identities", () => {
  expect(() => renderFunctionCatalog([
    entry("public.example(pg_catalog.text)"),
    entry("public.example(pg_catalog.text)"),
  ])).toThrow(/duplicate identities/);
});

test("resolves and writes the configured function catalog module", () => {
  const root = mkdtempSync(join(tmpdir(), "sqlx-js-functions-"));
  try {
    const config = { functionCatalog: { output: "src/db-functions.ts" } };
    const output = functionCatalogOutputPath(root, config)!;
    const content = renderFunctionCatalog([entry("public.example(pg_catalog.text)")]);
    writeFunctionCatalogModule(output, content);
    expect(readFileSync(output, "utf8")).toBe(content);
    expect(functionCatalogOutputPath(root, { functionCatalog: false })).toBeUndefined();
    expect(functionCatalogOutputPath(root, {})).toBeUndefined();
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("function output cannot collide with another generated artifact", () => {
  expect(() => assertDistinctPrepareGeneratedOutputs({
    root: "/project",
    config: {
      functionCatalog: { output: "src/generated.ts" },
      enumCatalog: { output: "src/generated.ts", schemas: ["public"] },
    },
    dtsPath: "/project/sqlx-js-env.d.ts",
  })).toThrow(/must be distinct/);
});
