import { inspectGeneratedGitAttributes } from "../generated-git-attributes";

export type GitAttributesDoctorCheck = {
  name: "gitAttributes";
  status: "ok" | "warning" | "error";
  message: string;
  fixable?: boolean;
  details?: Record<string, unknown>;
};

export function inspectGitAttributesDoctorCheck(
  root: string,
  dtsPath: string,
  additionalPaths: string[],
): GitAttributesDoctorCheck {
  try {
    const inspection = inspectGeneratedGitAttributes(root, dtsPath, additionalPaths);
    const incomplete = inspection.missing.length > 0 || inspection.unmanaged.length > 0;
    if (!incomplete) {
      return {
        name: "gitAttributes",
        status: "ok",
        message: "generated artifacts are marked as linguist-generated by project or repository attributes",
        details: { path: inspection.path, required: inspection.required },
      };
    }

    const missingMessage = inspection.missing.length > 0
      ? `${inspection.path} is missing ${inspection.missing.length} generated-artifact `
        + `${inspection.missing.length === 1 ? "rule" : "rules"}; run sqlx-js doctor --fix`
      : "";
    const unmanagedMessage = inspection.unmanaged.length > 0
      ? `${inspection.unmanaged.length} generated output `
        + `${inspection.unmanaged.length === 1 ? "is" : "are"} outside the project root and cannot be managed automatically`
      : "";
    return {
      name: "gitAttributes",
      status: "warning",
      message: [missingMessage, unmanagedMessage].filter(Boolean).join("; "),
      ...(inspection.missing.length > 0 ? { fixable: true } : {}),
      details: {
        path: inspection.path,
        required: inspection.required,
        missing: inspection.missing,
        unmanaged: inspection.unmanaged,
        ...(inspection.missing.length > 0 ? { fixCommand: "sqlx-js doctor --fix" } : {}),
      },
    };
  } catch (error) {
    return {
      name: "gitAttributes",
      status: "error",
      message: `cannot inspect generated Git attributes: ${(error as Error).message}`,
    };
  }
}
