import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const CONFIG_TEMPLATE = `import { defineConfig } from "@onreza/sqlx-js";

export default defineConfig({
  // Map jsonb columns/params to TypeScript types declared in a .d.ts, e.g.
  //   "users.settings": "SqlxJsJson.UserSettings",
  jsonbTypes: {},
  // Map PostgreSQL type names to TypeScript types, e.g.
  //   geometry: "GeoJSON.Geometry",
  customTypes: {},
});
`;

const PGSCHEMA_CONFIG_TEMPLATE = `import { defineConfig } from "@onreza/sqlx-js";

export default defineConfig({
  schema: {
    provider: "pgschema",
    file: "schema.sql",
    schemas: ["public"],
  },
  jsonbTypes: {},
  customTypes: {},
});
`;

const ENV_TEMPLATE = `# Connection string used by sqlx-js prepare/migrate and the runtime.
DATABASE_URL=postgres://user:password@localhost:5432/your_db
# Managed Postgres with TLS:
# DATABASE_URL=postgres://user:password@db.example.com:5432/your_db?sslmode=verify-full
`;

const PGSCHEMA_TEMPLATE = `-- Desired PostgreSQL schema managed by pgschema.
-- Edit this file, then run:
--   sqlx-js db plan -- --output-json plan.json
--   sqlx-js db apply -- --auto-approve
`;

const DTS_TEMPLATE = `// AUTO-GENERATED by sqlx-js. Do not edit.
// Run \`sqlx-js prepare\` to regenerate.

declare module "@onreza/sqlx-js" {
  interface KnownQueries {}
  interface KnownFileQueries {}
  interface KnownFunctions {}
}

export {};
`;

export type InitOptions = {
  root: string;
  schemaProvider?: "builtin" | "pgschema";
  log?: (msg: string) => void;
};

export function runInit(opts: InitOptions): void {
  const log = opts.log ?? console.log;
  const created: string[] = [];
  const updated: string[] = [];
  const skipped: string[] = [];
  const notes: string[] = [];

  const ensureFile = (rel: string, content: string) => {
    const full = join(opts.root, rel);
    if (existsSync(full)) {
      skipped.push(rel);
      return;
    }
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
    created.push(rel);
  };

  const ensureDir = (rel: string) => {
    const full = join(opts.root, rel);
    if (existsSync(full)) {
      skipped.push(`${rel}/`);
      return;
    }
    mkdirSync(full, { recursive: true });
    created.push(`${rel}/`);
  };

  const schemaProvider = opts.schemaProvider ?? "builtin";
  ensureFile("sqlx-js.config.ts", schemaProvider === "pgschema" ? PGSCHEMA_CONFIG_TEMPLATE : CONFIG_TEMPLATE);
  if (schemaProvider === "pgschema") ensureFile("schema.sql", PGSCHEMA_TEMPLATE);
  else ensureDir("migrations");
  ensureFile(".env.example", ENV_TEMPLATE);
  ensureFile("sqlx-js-env.d.ts", DTS_TEMPLATE);

  const updateJson = (rel: string, mutate: (value: Record<string, unknown>) => boolean) => {
    const full = join(opts.root, rel);
    if (!existsSync(full)) return;
    const source = readFileSync(full, "utf8");
    let value: unknown;
    try {
      value = JSON.parse(source);
    } catch {
      notes.push(`${rel}: manual update required because the file is not strict JSON`);
      return;
    }
    if (!value || typeof value !== "object" || Array.isArray(value)) return;
    if (!mutate(value as Record<string, unknown>)) return;
    const indent = source.match(/\n([ \t]+)"/)?.[1] ?? "  ";
    writeFileSync(full, JSON.stringify(value, null, indent) + "\n");
    updated.push(rel);
  };

  updateJson("tsconfig.json", (value) => {
    const files = value.files;
    if (files !== undefined && (!Array.isArray(files) || !files.every((item) => typeof item === "string"))) {
      notes.push("tsconfig.json: manual update required because files is not an array of strings");
      return false;
    }
    if (Array.isArray(files)) {
      if (files.includes("sqlx-js-env.d.ts")) return false;
      files.push("sqlx-js-env.d.ts");
      return true;
    }
    const include = value.include;
    if (include !== undefined && (!Array.isArray(include) || !include.every((item) => typeof item === "string"))) {
      notes.push("tsconfig.json: manual update required because include is not an array of strings");
      return false;
    }
    if (Array.isArray(include)) {
      if (include.includes("sqlx-js-env.d.ts")) return false;
      include.push("sqlx-js-env.d.ts");
      return true;
    }
    return false;
  });

  updateJson("package.json", (value) => {
    if (value.scripts !== undefined && (!value.scripts || typeof value.scripts !== "object" || Array.isArray(value.scripts))) {
      notes.push("package.json: manual script update required because scripts is not an object");
      return false;
    }
    const scripts = (value.scripts ??= {}) as Record<string, unknown>;
    const defaults = {
      "sqlx:prepare": "sqlx-js prepare",
      "sqlx:check": "sqlx-js prepare --check",
      "sqlx:verify": "sqlx-js prepare --verify --strict-inference",
    };
    let changed = false;
    for (const [name, command] of Object.entries(defaults)) {
      if (scripts[name] !== undefined) continue;
      scripts[name] = command;
      changed = true;
    }
    return changed;
  });

  for (const f of created) log(`created ${f}`);
  for (const f of updated) log(`updated ${f}`);
  for (const f of skipped) log(`exists  ${f} (left unchanged)`);
  for (const note of notes) log(`manual  ${note}`);

  log("");
  log("Next steps:");
  log("  1. Set DATABASE_URL (see .env.example).");
  if (schemaProvider === "pgschema") {
    log("  2. Install managed pgschema:  sqlx-js db install");
    log("  3. Verify it:  sqlx-js db check");
    log("  4. Edit schema.sql, then review:  sqlx-js db plan");
    log("  5. After applying schema changes, run:  sqlx-js prepare");
  } else {
    log("  2. Add a migration:  sqlx-js migrate add init");
    log("  3. Check the project setup:  sqlx-js doctor");
    log("  4. Develop locally:  sqlx-js migrate dev --strict-inference");
  }
}
