import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import {
  SQUASH_PREFIX,
  effectiveSquashReplacements,
  readMigrations,
  type MigrationFile,
  type SquashMetadata,
  type SquashReplacement,
} from "../migration-core";
import { parseDatabaseUrl } from "../pg/wire";

const FILE_RE = /^(\d+)_(.+)\.up\.sql$/;
const DOWN_FILE_RE = /^(\d+)_(.+)\.down\.sql$/;
const SAFE_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/;

export type MigrationArchive = {
  name: string;
  path: string;
  files: string[];
};

export function safeMigrationName(name: string): string {
  const safe = name.replace(/[^a-zA-Z0-9_-]+/g, "_").replace(/^[^a-zA-Z0-9]+/, "");
  if (!safe) throw new Error(`sqlx-js.migrate: invalid migration name "${name}"`);
  return safe;
}

function renderSquashMigration(replaces: SquashReplacement[], schemaSql: string): string {
  const metadata: SquashMetadata = { format: 1, replaces };
  return [
    `${SQUASH_PREFIX} ${JSON.stringify(metadata)}`,
    "-- generated by sqlx-js migrate squash",
    "-- This baseline can be applied to an empty database or adopted by a database",
    "-- that has all replaced migrations recorded with matching hashes.",
    "",
    schemaSql.trimEnd(),
    "",
  ].join("\n");
}

export function sanitizePgDumpSchema(sql: string): string {
  const out: string[] = [];
  let state: PgDumpScanState = { dollarQuote: null, blockComment: false, singleQuote: null };
  for (const line of sql.split(/\r?\n/)) {
    if (!state.dollarQuote && !state.blockComment && !state.singleQuote && line.trimStart().startsWith("\\")) continue;
    out.push(line);
    state = scanPgDumpLine(line, state);
  }
  return out.join("\n").trimEnd() + "\n";
}

type PgDumpScanState = {
  dollarQuote: string | null;
  blockComment: boolean;
  singleQuote: "standard" | "escape" | null;
};

function matchDollarQuote(line: string, index: number): string | null {
  const m = /^\$[A-Za-z_][A-Za-z0-9_]*\$|^\$\$/.exec(line.slice(index));
  return m?.[0] ?? null;
}

function scanPgDumpLine(line: string, current: PgDumpScanState): PgDumpScanState {
  const state = { ...current };
  let i = 0;
  while (i < line.length) {
    if (state.singleQuote) {
      while (i < line.length) {
        if (state.singleQuote === "escape" && line[i] === "\\") {
          i += 2;
          continue;
        }
        if (line[i] !== "'") {
          i++;
          continue;
        }
        if (line[i + 1] === "'") {
          i += 2;
          continue;
        }
        i++;
        state.singleQuote = null;
        break;
      }
      continue;
    }
    if (state.dollarQuote) {
      const end = line.indexOf(state.dollarQuote, i);
      if (end === -1) return state;
      i = end + state.dollarQuote.length;
      state.dollarQuote = null;
      continue;
    }
    if (state.blockComment) {
      const end = line.indexOf("*/", i);
      if (end === -1) return state;
      i = end + 2;
      state.blockComment = false;
      continue;
    }
    const ch = line[i];
    const next = line[i + 1];
    if (ch === "-" && next === "-") break;
    if (ch === "/" && next === "*") {
      state.blockComment = true;
      i += 2;
      continue;
    }
    if (ch === "'") {
      const escapeString = i > 0 && (line[i - 1] === "E" || line[i - 1] === "e");
      state.singleQuote = escapeString ? "escape" : "standard";
      i++;
      continue;
    }
    if (ch === "$") {
      const tag = matchDollarQuote(line, i);
      if (tag) {
        state.dollarQuote = tag;
        i += tag.length;
        continue;
      }
    }
    i++;
  }
  return state;
}

function archiveMigrations(migrationsDir: string, archiveName: string, migrations: MigrationFile[]): string {
  const archiveDir = join(migrationsDir, ".archive", archiveName);
  if (existsSync(archiveDir)) {
    throw new Error(`sqlx-js.migrate: archive already exists: ${archiveDir}`);
  }
  mkdirSync(archiveDir, { recursive: true });
  for (const m of migrations) {
    renameSync(m.upPath, join(archiveDir, basename(m.upPath)));
    if (m.downPath) renameSync(m.downPath, join(archiveDir, basename(m.downPath)));
  }
  return archiveDir;
}

function validateArchiveName(name: string): void {
  if (!SAFE_NAME_RE.test(name)) {
    throw new Error(`sqlx-js.migrate: unsafe archive name ${name}`);
  }
}

function isMigrationSqlFile(file: string): boolean {
  const up = FILE_RE.exec(file);
  const down = DOWN_FILE_RE.exec(file);
  const m = up ?? down;
  return !!m && SAFE_NAME_RE.test(m[2]!);
}

export function listMigrationArchives(migrationsDir: string): MigrationArchive[] {
  const archiveRoot = join(migrationsDir, ".archive");
  if (!existsSync(archiveRoot)) return [];
  return readdirSync(archiveRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && SAFE_NAME_RE.test(entry.name))
    .map((entry) => {
      const path = join(archiveRoot, entry.name);
      const files = readdirSync(path)
        .filter((file) => isMigrationSqlFile(file))
        .sort();
      return { name: entry.name, path, files };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function restoreMigrationArchive(
  migrationsDir: string,
  archiveName: string,
  opts: { force?: boolean } = {},
): { archiveName: string; restored: string[] } {
  validateArchiveName(archiveName);
  const archiveDir = join(migrationsDir, ".archive", archiveName);
  if (!existsSync(archiveDir)) {
    throw new Error(`sqlx-js.migrate: archive not found: ${archiveName}`);
  }
  const files = readdirSync(archiveDir)
    .filter((file) => isMigrationSqlFile(file))
    .sort();
  if (files.length === 0) throw new Error(`sqlx-js.migrate: archive is empty: ${archiveName}`);

  const conflicts = files.filter((file) => existsSync(join(migrationsDir, file)));
  if (conflicts.length > 0 && !opts.force) {
    throw new Error(`sqlx-js.migrate: restore would overwrite existing migration file(s): ${conflicts.join(", ")}`);
  }

  for (const file of files) {
    renameSync(join(archiveDir, file), join(migrationsDir, file));
  }
  return { archiveName, restored: files };
}

export function createSquashMigration(opts: {
  migrationsDir: string;
  name: string;
  schemaSql: string;
  replace?: boolean;
}): { version: number; name: string; upPath: string; replaced: number; archiveDir?: string } {
  if (!existsSync(opts.migrationsDir)) mkdirSync(opts.migrationsDir, { recursive: true });
  const existing = readMigrations(opts.migrationsDir);
  if (existing.length === 0) throw new Error("sqlx-js.migrate: no migrations to squash");
  if (opts.schemaSql.trim() === "") throw new Error("sqlx-js.migrate: squash schema SQL is empty");

  const safe = safeMigrationName(opts.name);
  const nextVersion = (existing[existing.length - 1]?.version ?? 0) + 1;
  const padded = String(nextVersion).padStart(4, "0");
  const upPath = join(opts.migrationsDir, `${padded}_${safe}.up.sql`);
  if (existsSync(upPath)) throw new Error(`sqlx-js.migrate: migration already exists: ${upPath}`);

  const replaces = effectiveSquashReplacements(existing);
  writeFileSync(upPath, renderSquashMigration(replaces, opts.schemaSql));

  let archiveDir: string | undefined;
  if (opts.replace) {
    archiveDir = archiveMigrations(opts.migrationsDir, `${padded}_${safe}`, existing);
  }

  return { version: nextVersion, name: safe, upPath, replaced: replaces.length, archiveDir };
}

function pgDumpEnv(databaseUrl: string): NodeJS.ProcessEnv {
  const cfg = parseDatabaseUrl(databaseUrl);
  const env: NodeJS.ProcessEnv = { ...process.env };
  env.PGHOST = cfg.host;
  env.PGPORT = String(cfg.port);
  env.PGUSER = cfg.user;
  env.PGDATABASE = cfg.database;
  if (cfg.password) env.PGPASSWORD = cfg.password;
  else delete env.PGPASSWORD;
  if (cfg.sslmode) env.PGSSLMODE = cfg.sslmode;
  else delete env.PGSSLMODE;
  if (cfg.applicationName) env.PGAPPNAME = cfg.applicationName;
  else delete env.PGAPPNAME;
  if (cfg.connectTimeoutMs) env.PGCONNECT_TIMEOUT = String(cfg.connectTimeoutMs / 1000);
  else delete env.PGCONNECT_TIMEOUT;
  delete env.PGSERVICE;
  delete env.PGSERVICEFILE;
  delete env.PGPASSFILE;
  return env;
}

export function dumpSchema(databaseUrl: string, pgDumpPath = "pg_dump"): string {
  const tmp = mkdtempSync(join(tmpdir(), "sqlx-js-pgdump-"));
  const outPath = join(tmp, "schema.sql");
  const args = [
    "--schema-only",
    "--no-owner",
    "--no-privileges",
    "--exclude-table=*._sqlx_js_migrations",
    "--exclude-table=_sqlx_js_migrations",
    "--exclude-table=public._sqlx_js_migrations",
    `--file=${outPath}`,
    "-w",
  ];
  try {
    const r = spawnSync(pgDumpPath, args, {
      encoding: "utf8",
      env: pgDumpEnv(databaseUrl),
      maxBuffer: 16 * 1024 * 1024,
    });
    if (r.error) {
      throw new Error(`sqlx-js.migrate: failed to run ${pgDumpPath}: ${r.error.message}`);
    }
    if (r.status !== 0) {
      throw new Error(`sqlx-js.migrate: ${pgDumpPath} failed: ${r.stderr.trim() || `exit ${r.status}`}`);
    }
    const schema = sanitizePgDumpSchema(readFileSync(outPath, "utf8"));
    if (schema.trim() === "") throw new Error("sqlx-js.migrate: pg_dump returned empty schema");
    return schema;
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}
