// AUTO-GENERATED by sqlx-js. Do not edit.
// Run `sqlx-js prepare` to regenerate.

export interface SqlxJsGeneratedQueries {
  "SELECT id, name FROM pgschema_probe WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string } };
}

export interface SqlxJsGeneratedFileQueries {
}

export interface SqlxJsGeneratedFunctions {
  "public.pgschema_normalize_name(value text)": { kind: "function"; language: "sql"; params: [string | null]; returns: string | null; returnsSet: false; volatility: "immutable"; strict: true; securityDefiner: false; leakproof: false; parallelSafety: "unsafe"; owner: "postgres"; ownerSuperuser: true; publicExecute: true; settings: readonly []; searchPath: null; extensionOwned: false };
}

export interface SqlxJsGeneratedRuntimeTypes {
}

export interface SqlxJsGeneratedProfileQueries {
}

export interface SqlxJsGeneratedProfileFileQueries {
}

export interface SqlxJsGeneratedProfiles {
}

export type SqlxJsGeneratedProfileRegistry<Name extends keyof SqlxJsGeneratedProfiles> = SqlxJsGeneratedProfiles[Name];

export interface SqlxJsGeneratedRegistry {
  queries: SqlxJsGeneratedQueries;
  fileQueries: SqlxJsGeneratedFileQueries;
  functions: SqlxJsGeneratedFunctions;
  runtimeTypes: SqlxJsGeneratedRuntimeTypes;
  runtimeDescriptors: true;
  jsonProtocol: 1;
  temporal: { readonly infinity: "reject"; readonly timestampWithoutTimeZone: "reject"; readonly sessionTimeZone: "UTC" };
}
