// AUTO-GENERATED by sqlx-js. Do not edit.
// Run `sqlx-js prepare` to regenerate.

export interface SqlxJsGeneratedQueries<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
  "SELECT id, name FROM pgschema_probe WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string } };
}

export interface SqlxJsGeneratedFileQueries<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
}

export interface SqlxJsGeneratedFunctions<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
  "public.pgschema_normalize_name(value text)": { kind: "function"; language: "sql"; params: [string | null]; returns: string | null; returnsSet: false; volatility: "immutable"; strict: true; securityDefiner: false; leakproof: false; parallelSafety: "unsafe"; owner: "postgres"; ownerSuperuser: true; publicExecute: true; settings: readonly ["search_path=public, pg_catalog, pg_temp", "TimeZone=UTC"]; searchPath: "public, pg_catalog, pg_temp"; extensionOwned: false };
}

export interface SqlxJsGeneratedRuntimeTypes {
}

export interface SqlxJsGeneratedProfileQueries<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
}

export interface SqlxJsGeneratedProfileFileQueries<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
}

export interface SqlxJsGeneratedProfiles<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
}

export type SqlxJsGeneratedProfileRegistry<Name extends keyof SqlxJsGeneratedProfiles, TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> = SqlxJsGeneratedProfiles<TemporalProvider>[Name];

export interface SqlxJsGeneratedRegistry<TemporalProvider extends import("@onreza/sqlx-js").TemporalApi = import("@onreza/sqlx-js").GlobalTemporalApi> {
  queries: SqlxJsGeneratedQueries<TemporalProvider>;
  fileQueries: SqlxJsGeneratedFileQueries<TemporalProvider>;
  functions: SqlxJsGeneratedFunctions<TemporalProvider>;
  runtimeTypes: SqlxJsGeneratedRuntimeTypes;
  runtimeDescriptors: true;
  jsonProtocol: 1;
  temporal: { readonly infinity: "reject"; readonly timestampWithoutTimeZone: "reject"; readonly sessionTimeZone: "UTC" };
  temporalApi: TemporalProvider;
}
