// AUTO-GENERATED by sqlx-js. Do not edit.
// Run `sqlx-js prepare` to regenerate.

export interface SqlxJsGeneratedQueries {
  "SELECT id, name FROM pgschema_probe WHERE id = $1": { params: [bigint]; row: { "id": bigint; "name": string } };
}

export interface SqlxJsGeneratedFileQueries {
}

export interface SqlxJsGeneratedFunctions {
  "public.pgschema_normalize_name(value text)": { kind: "function"; params: [string]; returns: string | null; returnsSet: false; volatility: "immutable"; securityDefiner: false; leakproof: false; parallelSafety: "unsafe"; owner: "postgres"; ownerSuperuser: true; publicExecute: true; searchPath: null; extensionOwned: false };
}

export interface SqlxJsGeneratedRuntimeTypes {
}

export interface SqlxJsGeneratedProfileQueries {
}

export interface SqlxJsGeneratedProfileFileQueries {
}

export interface SqlxJsGeneratedProfiles {
}

export interface SqlxJsGeneratedRegistry {
  queries: SqlxJsGeneratedQueries;
  fileQueries: SqlxJsGeneratedFileQueries;
  functions: SqlxJsGeneratedFunctions;
  runtimeTypes: SqlxJsGeneratedRuntimeTypes;
}

declare module "@onreza/sqlx-js" {
  interface KnownQueries extends SqlxJsGeneratedQueries {}
  interface KnownFileQueries extends SqlxJsGeneratedFileQueries {}
  interface KnownFunctions extends SqlxJsGeneratedFunctions {}
  interface KnownProfiles extends SqlxJsGeneratedProfiles {}
}

export {};
