import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { effectiveNullable, type CacheEntry } from "./cache";

function entrySignature(e: CacheEntry): { params: string; row: string } {
  const paramTypes = e.paramTsTypes.map((t, i) => {
    const nullable = e.paramNullable?.[i] === true;
    return nullable ? `${t} | null` : t;
  });
  const params = paramTypes.length === 0 ? "[]" : `[${paramTypes.join(", ")}]`;
  if (!e.hasResultSet) return { params, row: "never" };
  const cols = e.columns.map((c) => {
    const nullable = effectiveNullable(c);
    const t = nullable ? `${c.tsType} | null` : c.tsType;
    return `${JSON.stringify(c.name)}: ${t}`;
  });
  return { params, row: `{ ${cols.join("; ")} }` };
}

export function emitDts(outPath: string, entries: CacheEntry[]): void {
  mkdirSync(dirname(outPath), { recursive: true });
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by sqlx-js. Do not edit.");
  lines.push("// Run `sqlx-js prepare` to regenerate.");
  lines.push("");
  emitModule(lines, "@onreza/sqlx-js", entries);
  lines.push("");
  lines.push("export {};");
  writeFileSync(outPath, lines.join("\n") + "\n");
}

function emitModule(lines: string[], moduleName: string, entries: CacheEntry[]): void {
  lines.push(`declare module ${JSON.stringify(moduleName)} {`);
  lines.push("  interface KnownQueries {");

  const inlineSeen = new Set<string>();
  const inlinePairs: { query: string; entry: CacheEntry }[] = [];
  for (const e of entries) {
    const emitInline = e.hasInline === true || (e.hasInline !== false && (!e.filePaths || e.filePaths.length === 0));
    if (!emitInline) continue;
    const queries = e.inlineQueries && e.inlineQueries.length > 0 ? e.inlineQueries : [e.query];
    for (const query of queries) inlinePairs.push({ query, entry: e });
  }
  for (const { query, entry } of inlinePairs.slice().sort((a, b) => a.query.localeCompare(b.query))) {
    if (inlineSeen.has(query)) continue;
    inlineSeen.add(query);
    const { params, row } = entrySignature(entry);
    if (entry.degraded) lines.push(`    /** Nullability inference degraded: ${entry.degraded.reason}. All result columns conservatively typed as nullable. */`);
    lines.push(`    ${JSON.stringify(query)}: { params: ${params}; row: ${row} };`);
  }

  lines.push("  }");
  lines.push("");
  lines.push("  interface KnownFileQueries {");

  const filePairs: { path: string; entry: CacheEntry }[] = [];
  for (const e of entries) {
    if (!e.filePaths || e.filePaths.length === 0) continue;
    for (const p of e.filePaths) filePairs.push({ path: p, entry: e });
  }
  const filePathsSeen = new Set<string>();
  for (const { path, entry } of filePairs.slice().sort((a, b) => a.path.localeCompare(b.path))) {
    if (filePathsSeen.has(path)) continue;
    filePathsSeen.add(path);
    const { params, row } = entrySignature(entry);
    if (entry.degraded) lines.push(`    /** Nullability inference degraded: ${entry.degraded.reason}. */`);
    lines.push(`    ${JSON.stringify(path)}: { params: ${params}; row: ${row} };`);
  }

  lines.push("  }");
  lines.push("}");
}
