import { writeFileSync, mkdirSync, renameSync, unlinkSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname } from "node:path";
import { effectiveNullable, type CacheEntry } from "./cache";
import type { FunctionEntry } from "./function-cache";
import type { DatabaseProfiles } from "./config";

function entrySignature(e: CacheEntry): { params: string; row: string } {
  const paramTypes = e.paramTsTypes.map((t, i) => {
    const nullable = e.paramNullable?.[i] === true;
    return nullable ? `${t} | null` : t;
  });
  const params = e.paramNames && e.paramNames.length > 0
    ? `{ ${e.paramNames.map((name, index) => `${JSON.stringify(name)}: ${paramTypes[index]}`).join("; ")} }`
    : paramTypes.length === 0 ? "[]" : `[${paramTypes.join(", ")}]`;
  if (!e.hasResultSet) return { params, row: "never" };
  const cols = e.columns.map((c) => {
    const nullable = effectiveNullable(c);
    const t = nullable ? `${c.tsType} | null` : c.tsType;
    return `${JSON.stringify(c.name)}: ${t}`;
  });
  return { params, row: `{ ${cols.join("; ")} }` };
}

export function emitDts(
  outPath: string,
  entries: CacheEntry[],
  functions: FunctionEntry[] = [],
  runtimeTypes: Readonly<Record<string, string>> = {},
  profiles: DatabaseProfiles = {},
): void {
  mkdirSync(dirname(outPath), { recursive: true });
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by sqlx-js. Do not edit.");
  lines.push("// Run `sqlx-js prepare` to regenerate.");
  lines.push("");
  emitRegistry(lines, entries, functions, runtimeTypes, profiles);
  lines.push("");
  emitModuleAugmentation(lines, "@onreza/sqlx-js");
  lines.push("");
  lines.push("export {};");
  const tmp = `${outPath}.tmp-${randomBytes(4).toString("hex")}`;
  writeFileSync(tmp, lines.join("\n") + "\n");
  try {
    renameSync(tmp, outPath);
  } catch (err) {
    try { unlinkSync(tmp); } catch {}
    throw err;
  }
}

function emitRegistry(
  lines: string[],
  entries: CacheEntry[],
  functions: FunctionEntry[],
  runtimeTypes: Readonly<Record<string, string>>,
  profiles: DatabaseProfiles,
): void {
  const defaultEntries = Object.keys(profiles).length === 0
    ? entries
    : entries.filter((entry) => entry.profile === undefined);
  lines.push("export interface SqlxJsGeneratedQueries {");
  emitInlineProperties(lines, defaultEntries, "  ");
  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedFileQueries {");
  emitFileProperties(lines, defaultEntries, "  ");
  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedFunctions {");

  const functionSeen = new Set<string>();
  for (const fn of functions.slice().sort((a, b) => a.signature.localeCompare(b.signature))) {
    if (functionSeen.has(fn.signature)) continue;
    functionSeen.add(fn.signature);
    const params = inputParams(fn);
    const searchPath = fn.searchPath === null ? "null" : JSON.stringify(fn.searchPath);
    lines.push(
      `  ${JSON.stringify(fn.signature)}: { kind: ${JSON.stringify(fn.kind)}; params: ${params}; `
      + `returns: ${fn.returns}; returnsSet: ${fn.returnsSet}; volatility: ${JSON.stringify(fn.volatility)}; `
      + `securityDefiner: ${fn.securityDefiner}; leakproof: ${fn.leakproof}; `
      + `parallelSafety: ${JSON.stringify(fn.parallelSafety)}; owner: ${JSON.stringify(fn.owner)}; `
      + `ownerSuperuser: ${fn.ownerSuperuser}; publicExecute: ${fn.publicExecute}; `
      + `searchPath: ${searchPath}; extensionOwned: ${fn.extensionOwned} };`,
    );
  }

  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedRuntimeTypes {");

  for (const [name, type] of Object.entries(runtimeTypes).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(name)}: ${type};`);
  }

  lines.push("}");
  lines.push("");
  emitProfileRegistries(lines, entries, profiles);
  lines.push("");
  lines.push("export interface SqlxJsGeneratedRegistry {");
  lines.push("  queries: SqlxJsGeneratedQueries;");
  lines.push("  fileQueries: SqlxJsGeneratedFileQueries;");
  lines.push("  functions: SqlxJsGeneratedFunctions;");
  lines.push("  runtimeTypes: SqlxJsGeneratedRuntimeTypes;");
  lines.push("}");
}

function emitModuleAugmentation(lines: string[], moduleName: string): void {
  lines.push(`declare module ${JSON.stringify(moduleName)} {`);
  lines.push("  interface KnownQueries extends SqlxJsGeneratedQueries {}");
  lines.push("  interface KnownFileQueries extends SqlxJsGeneratedFileQueries {}");
  lines.push("  interface KnownFunctions extends SqlxJsGeneratedFunctions {}");
  lines.push("  interface KnownProfiles extends SqlxJsGeneratedProfiles {}");
  lines.push("}");
}

function emitProfileRegistries(
  lines: string[],
  entries: CacheEntry[],
  profiles: DatabaseProfiles,
): void {
  lines.push("export interface SqlxJsGeneratedProfileQueries {");
  for (const [name] of Object.entries(profiles).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(name)}: {`);
    emitInlineProperties(lines, entries.filter((entry) => entry.profile === name), "    ");
    lines.push("  };");
  }
  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedProfileFileQueries {");
  for (const [name] of Object.entries(profiles).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(name)}: {`);
    emitFileProperties(lines, entries.filter((entry) => entry.profile === name), "    ");
    lines.push("  };");
  }
  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedProfiles {");
  for (const [name, profile] of Object.entries(profiles).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(name)}: {`);
    lines.push(`    queries: SqlxJsGeneratedProfileQueries[${JSON.stringify(name)}];`);
    lines.push(`    fileQueries: SqlxJsGeneratedProfileFileQueries[${JSON.stringify(name)}];`);
    lines.push("    functions: SqlxJsGeneratedFunctions;");
    lines.push("    runtimeTypes: SqlxJsGeneratedRuntimeTypes;");
    const transactionSettings = profile.transactionSettings
      ? ` readonly transactionSettings: readonly [${profile.transactionSettings.map((setting) => JSON.stringify(setting)).join(", ")}];`
      : "";
    lines.push(
      `    profile: { readonly name: ${JSON.stringify(name)}; readonly role: ${JSON.stringify(profile.role)};${transactionSettings} };`,
    );
    lines.push("  };");
  }
  lines.push("}");
}

function emitInlineProperties(lines: string[], entries: CacheEntry[], indent: string): void {
  const seen = new Set<string>();
  const pairs: { query: string; entry: CacheEntry }[] = [];
  for (const entry of entries) {
    const emitInline = entry.hasInline === true ||
      (entry.hasInline !== false && (!entry.filePaths || entry.filePaths.length === 0));
    if (!emitInline) continue;
    const queries = entry.inlineQueries && entry.inlineQueries.length > 0
      ? entry.inlineQueries
      : [entry.query];
    for (const query of queries) pairs.push({ query, entry });
  }
  for (const { query, entry } of pairs.sort((a, b) => a.query.localeCompare(b.query))) {
    if (seen.has(query)) continue;
    seen.add(query);
    const { params, row } = entrySignature(entry);
    if (entry.degraded) {
      lines.push(
        `${indent}/** Nullability inference degraded: ${entry.degraded.reason}. All result columns conservatively typed as nullable. */`,
      );
    }
    lines.push(`${indent}${JSON.stringify(query)}: { params: ${params}; row: ${row} };`);
  }
}

function emitFileProperties(lines: string[], entries: CacheEntry[], indent: string): void {
  const pairs: { path: string; entry: CacheEntry }[] = [];
  for (const entry of entries) {
    for (const path of entry.filePaths ?? []) pairs.push({ path, entry });
  }
  const seen = new Set<string>();
  for (const { path, entry } of pairs.sort((a, b) => a.path.localeCompare(b.path))) {
    if (seen.has(path)) continue;
    seen.add(path);
    const { params, row } = entrySignature(entry);
    if (entry.degraded) {
      lines.push(`${indent}/** Nullability inference degraded: ${entry.degraded.reason}. */`);
    }
    lines.push(`${indent}${JSON.stringify(path)}: { params: ${params}; row: ${row} };`);
  }
}

function inputParams(fn: FunctionEntry): string {
  const params = fn.params
    .filter((p) => p.mode === "in" || p.mode === "inout" || p.mode === "variadic")
    .map((p) => p.tsType);
  return params.length === 0 ? "[]" : `[${params.join(", ")}]`;
}
