import { writeFileSync, mkdirSync, renameSync, unlinkSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname } from "node:path";
import { effectiveNullable, type CacheEntry } from "./cache";
import type { FunctionEntry } from "./function-cache";

function entrySignature(e: CacheEntry): { params: string; row: string } {
  const paramTypes = e.paramTsTypes.map((t, i) => {
    const nullable = e.paramNullable?.[i] === true;
    return nullable ? `${t} | null` : t;
  });
  const params = e.paramNames && e.paramNames.length > 0
    ? `{ ${e.paramNames.map((name, index) => `${JSON.stringify(name)}: ${paramTypes[index]}`).join("; ")} }`
    : paramTypes.length === 0 ? "[]" : `[${paramTypes.join(", ")}]`;
  if (!e.hasResultSet) return { params, row: "never" };
  const cols = e.columns.map((c) => {
    const nullable = effectiveNullable(c);
    const t = nullable ? `${c.tsType} | null` : c.tsType;
    return `${JSON.stringify(c.name)}: ${t}`;
  });
  return { params, row: `{ ${cols.join("; ")} }` };
}

export function emitDts(outPath: string, entries: CacheEntry[], functions: FunctionEntry[] = []): void {
  mkdirSync(dirname(outPath), { recursive: true });
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by sqlx-js. Do not edit.");
  lines.push("// Run `sqlx-js prepare` to regenerate.");
  lines.push("");
  emitRegistry(lines, entries, functions);
  lines.push("");
  emitModuleAugmentation(lines, "@onreza/sqlx-js");
  lines.push("");
  lines.push("export {};");
  const tmp = `${outPath}.tmp-${randomBytes(4).toString("hex")}`;
  writeFileSync(tmp, lines.join("\n") + "\n");
  try {
    renameSync(tmp, outPath);
  } catch (err) {
    try { unlinkSync(tmp); } catch {}
    throw err;
  }
}

function emitRegistry(lines: string[], entries: CacheEntry[], functions: FunctionEntry[]): void {
  lines.push("export interface SqlxJsGeneratedQueries {");

  const inlineSeen = new Set<string>();
  const inlinePairs: { query: string; entry: CacheEntry }[] = [];
  for (const e of entries) {
    const emitInline = e.hasInline === true || (e.hasInline !== false && (!e.filePaths || e.filePaths.length === 0));
    if (!emitInline) continue;
    const queries = e.inlineQueries && e.inlineQueries.length > 0 ? e.inlineQueries : [e.query];
    for (const query of queries) inlinePairs.push({ query, entry: e });
  }
  for (const { query, entry } of inlinePairs.slice().sort((a, b) => a.query.localeCompare(b.query))) {
    if (inlineSeen.has(query)) continue;
    inlineSeen.add(query);
    const { params, row } = entrySignature(entry);
    if (entry.degraded) lines.push(`  /** Nullability inference degraded: ${entry.degraded.reason}. All result columns conservatively typed as nullable. */`);
    lines.push(`  ${JSON.stringify(query)}: { params: ${params}; row: ${row} };`);
  }

  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedFileQueries {");

  const filePairs: { path: string; entry: CacheEntry }[] = [];
  for (const e of entries) {
    if (!e.filePaths || e.filePaths.length === 0) continue;
    for (const p of e.filePaths) filePairs.push({ path: p, entry: e });
  }
  const filePathsSeen = new Set<string>();
  for (const { path, entry } of filePairs.slice().sort((a, b) => a.path.localeCompare(b.path))) {
    if (filePathsSeen.has(path)) continue;
    filePathsSeen.add(path);
    const { params, row } = entrySignature(entry);
    if (entry.degraded) lines.push(`  /** Nullability inference degraded: ${entry.degraded.reason}. */`);
    lines.push(`  ${JSON.stringify(path)}: { params: ${params}; row: ${row} };`);
  }

  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedFunctions {");

  const functionSeen = new Set<string>();
  for (const fn of functions.slice().sort((a, b) => a.signature.localeCompare(b.signature))) {
    if (functionSeen.has(fn.signature)) continue;
    functionSeen.add(fn.signature);
    const params = inputParams(fn);
    lines.push(`  ${JSON.stringify(fn.signature)}: { kind: ${JSON.stringify(fn.kind)}; params: ${params}; returns: ${fn.returns}; returnsSet: ${fn.returnsSet} };`);
  }

  lines.push("}");
  lines.push("");
  lines.push("export interface SqlxJsGeneratedRegistry {");
  lines.push("  queries: SqlxJsGeneratedQueries;");
  lines.push("  fileQueries: SqlxJsGeneratedFileQueries;");
  lines.push("  functions: SqlxJsGeneratedFunctions;");
  lines.push("}");
}

function emitModuleAugmentation(lines: string[], moduleName: string): void {
  lines.push(`declare module ${JSON.stringify(moduleName)} {`);
  lines.push("  interface KnownQueries extends SqlxJsGeneratedQueries {}");
  lines.push("  interface KnownFileQueries extends SqlxJsGeneratedFileQueries {}");
  lines.push("  interface KnownFunctions extends SqlxJsGeneratedFunctions {}");
  lines.push("}");
}

function inputParams(fn: FunctionEntry): string {
  const params = fn.params
    .filter((p) => p.mode === "in" || p.mode === "inout" || p.mode === "variadic")
    .map((p) => p.tsType);
  return params.length === 0 ? "[]" : `[${params.join(", ")}]`;
}
