import { resolve } from "node:path";
import type { CacheEntry } from "./cache";
import type { SqlxJsConfig } from "./config";
import type { QueryCallSite } from "./scan/scanner";

export function embeddedSqlOutputPath(
  root: string,
  config: SqlxJsConfig,
  override?: string,
): string | undefined {
  if (!config.sqlFiles) return undefined;
  return override ?? resolve(root, config.sqlFiles.output);
}

export function renderEmbeddedSqlModule(entries: readonly CacheEntry[]): string {
  const files = new Map<string, string>();
  for (const entry of entries) {
    for (const path of entry.filePaths ?? []) {
      const previous = files.get(path);
      if (previous !== undefined && previous !== entry.query) {
        throw new Error(`sqlx-js: SQL file ${JSON.stringify(path)} resolves to multiple query texts`);
      }
      files.set(path, entry.query);
    }
  }
  return renderEmbeddedSqlFiles(files);
}

export function renderEmbeddedSqlModuleFromSites(sites: readonly QueryCallSite[]): string {
  const files = new Map<string, string>();
  for (const site of sites) {
    if (site.kind !== "file" || !site.sqlFilePath) continue;
    const previous = files.get(site.sqlFilePath);
    if (previous !== undefined && previous !== site.query) {
      throw new Error(`sqlx-js: SQL file ${JSON.stringify(site.sqlFilePath)} resolves to multiple query texts`);
    }
    files.set(site.sqlFilePath, site.query);
  }
  return renderEmbeddedSqlFiles(files);
}

function renderEmbeddedSqlFiles(files: ReadonlyMap<string, string>): string {
  const entries = [...files]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, query]) => `  [${JSON.stringify(path)}]: ${JSON.stringify(query)},`);
  return [
    "// AUTO-GENERATED by sqlx-js. Do not edit.",
    "// Run `sqlx-js prepare` to regenerate.",
    "",
    "export const sqlxJsEmbeddedSql = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
}
