import { resolve } from "node:path";
import type { CacheEntry } from "./cache";
import type { SqlxJsConfig } from "./config";

export function embeddedSqlOutputPath(
  root: string,
  config: SqlxJsConfig,
  override?: string,
): string | undefined {
  if (!config.sqlFiles) return undefined;
  return override ?? resolve(root, config.sqlFiles.output);
}

export function renderEmbeddedSqlModule(entries: readonly CacheEntry[]): string {
  const files = new Map<string, string>();
  for (const entry of entries) {
    for (const path of entry.filePaths ?? []) {
      const previous = files.get(path);
      if (previous !== undefined && previous !== entry.query) {
        throw new Error(`sqlx-js: SQL file ${JSON.stringify(path)} resolves to multiple query texts`);
      }
      files.set(path, entry.query);
    }
  }
  const sqlFiles = Object.fromEntries([...files].sort(([a], [b]) => a.localeCompare(b)));
  return [
    "// AUTO-GENERATED by sqlx-js. Do not edit.",
    "// Run `sqlx-js prepare` to regenerate.",
    "",
    `export const sqlxJsEmbeddedSql = ${JSON.stringify(sqlFiles, null, 2)} as const;`,
    "",
  ].join("\n");
}
