import { randomBytes } from "node:crypto";
import { mkdirSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { SqlxJsConfig } from "./config";
import type { FunctionEntry } from "./function-cache";

export function functionCatalogOutputPath(
  root: string,
  config: SqlxJsConfig,
  override?: string,
): string | undefined {
  if (config.functionCatalog === false || !config.functionCatalog?.output) return undefined;
  return override ?? resolve(root, config.functionCatalog.output);
}

export function renderFunctionCatalog(functions: readonly FunctionEntry[]): string {
  const identities = functions.map((fn) => fn.identity).sort(compareText);
  if (new Set(identities).size !== identities.length) {
    throw new Error("sqlx-js: function catalog contains duplicate identities");
  }
  const lines = [
    "// AUTO-GENERATED by sqlx-js. Do not edit.",
    "// Run `sqlx-js prepare` to regenerate.",
    "",
    "export const DbFunctions = {",
  ];
  for (const identity of identities) {
    lines.push(`  ${JSON.stringify(identity)}: ${JSON.stringify(identity)},`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type DbFunctionIdentity = keyof typeof DbFunctions;");
  lines.push("");
  return lines.join("\n");
}

export function writeFunctionCatalogModule(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp-${randomBytes(4).toString("hex")}`;
  writeFileSync(tmp, content);
  try {
    renameSync(tmp, path);
  } catch (error) {
    try { unlinkSync(tmp); } catch {}
    throw error;
  }
}

function compareText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}
